apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly-iii-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: "/var/mnt/data"
