apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly-iii-upload-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/mnt/data"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly-iii-db-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/mnt/data"
